# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('availability_start', models.DateTimeField(default=datetime.datetime.now)),
                ('availability_end', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('available', 'RoomAvailable'), ('not_available', 'RoomNotAvailable'), ('reserved', 'RoomReserved'), ('confirmed', 'RoomConfirmed')], default='available', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
