# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 22:49
from __future__ import unicode_literals

from django.db import migrations


def create_equipments(apps, schema_editor):
    Equipment = apps.get_model('meeting_room', 'Equipment')
    equipments = ['Pizarrón', 'Proyector']

    for equip in equipments:
        new_equip = Equipment(name=equip)
        new_equip.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0002_auto_20170508_2345'),
    ]

    operations = [
        migrations.RunPython(create_equipments),
    ]
