# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0005_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='availability_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Disponible hasta'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='availability_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Disponible desde'),
        ),
    ]
