# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0006_auto_20170510_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='equipments',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Equipos'),
        ),
    ]
